### ISSUE TITLE
Prepare for hookathon

### ISSUE THREAD

**Issue by MattPereira** [balancer/scaffold-balancer-v3#69]
### Tasks
- [x] Add a third deploy script example for a simple weighted pool
- [x] Make sure hooks video is finalized for publish
- [x] Update each deploy script to use a different hook example
- [x] Fix / improve styles on the pool hooks page
- [x] Record new intro to scaffold video for the Quickstart section of README

**Comment by MattPereira** [comment]
## Obstacle
Frontend is not ready for pools that set `disableUnbalancedLiquidity: true` which is required for the `LotteryHook` and `ExitFeeHook`
- [ ] Figure out how to use `AddLiquidityKind.Proportional` with the SDK
- [ ] Figure out UI for proportional add liquidity
- [ ] Figure out how to identify if pool type is custom or weighted so front-end can use the correct ABI

![image](https://github.com/user-attachments/assets/4381a758-8736-4023-954c-3e542385a9bb)
